site_name: python_pkg_template
theme:
  name: material
plugins:
- search
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        options:
          heading_level: 2
          show_root_heading: True
          show_source: False
